version: "3.7"  
services:  
  dev:  
    build:  
      context: .  
      target: build  
    volumes:  
    - ./:/app  
    - /app/node_modules  
    ports:  
    - 3000:3000  
    command: npm run dev